version: "2"
services:

  bitcoind:
    image: jamesob/bitcoind
    expose:
      - "8332"
    ports:
      - "8333:8333"
    volumes:
      - ./data/bitcoind:/root/.bitcoin
    environment:
      - BTC_RPCUSER=electrum
      - BTC_RPCPASSWORD=electrum
      - BTC_TXINDEX=1

  electrumx:
    image: lukechilds/electrumx
    ports:
      - "55002:50002"
    volumes:
      - ./data/electrumx:/data
    environment:
      - DAEMON_URL=http://electrum:electrum@bitcoind:8332
      - COIN=BitcoinSegwit

